name: Github Pages

on:
  push:
    branches:
      - main # Here source code branch is `master`, it could be other branch
      - fix-workflow
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'latest'
          bundler-cache: true
      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          provider: "github"
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          repository: "" # Default is current repository
          branch: "gh-pages" # Default is gh-pages for github provider
          jekyll_src: "./" # Default is root directory
          jekyll_cfg: "_config.yml" # Default is _config.yml
          jekyll_baseurl: "/jekyll-theme-yat" # Default is empty
          cname: "" # Default is to not use a cname
          actor: "" # Default is the GITHUB_ACTOR
